---
version: "3"

services:
  mongo:
    image: mongo
    container_name: monogo
    restart: always
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: comviz
      MONGO_INITDB_ROOT_PASSWORD: comviz101

  mongo-express:
    image: mongo-express
    container_name: monogo-expres
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: comviz
      ME_CONFIG_MONGODB_ADMINPASSWORD: comviz101
      ME_CONFIG_MONGODB_URL: mongodb://comviz:comviz101@mongo:27017/
    depends_on:
      - mongo

  trino:
    image: trinodb/trino
    container_name: trino
    volumes:
      - ./catalog:/etc/catalog
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - mongo-express

volumes:
  mongodb:
